# Generated by Django 6.0.4 on 2026-04-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_tender_admin_tender_posted_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='posted_by_admin',
        ),
        migrations.AddField(
            model_name='tender',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_posted', to='procurement.adminprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONTRACTOR', 'Contractor')], default='CONTRACTOR', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
