# Generated by Django 6.0.4 on 2026-06-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_notification_link_tenderrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
